# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191005_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=2, verbose_name='数量')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='所选商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='购物车用户')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
            },
        ),
    ]
