# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='所选商品'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='购物车用户'),
        ),
    ]
